services:
  postgresdb:
    image: postgres:15
    restart: unless-stopped
    container_name: postgresdb

    environment:
      POSTGRES_USER: somnia
      POSTGRES_PASSWORD: somnia
      POSTGRES_DB: form

    ports:
      - "5434:5432"

    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
